version: '3.4'

services:
  boxweb:
    image: boxweb
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
  boxweb-client:
    image: boxweb-client
    build:
      context: /web
      dockerfile: Dockerfile
    ports:
      - 5000:5000
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME:root
      - MONGO_INITDB_ROOT_PASSWORD:root
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME:root 
      - ME_CONFIG_MONGODB_ADMINPASSWORD:root 
      - ME_CONFIG_MONGODB_URL:mongodb://root:root@mongo:27017/
  ethereum:
    image: ethereum/client-go
    ports:
      - 30303:30303